#%RAML 1.0 Library

types:
  retrieveStudentResponse:
    properties:
      studentId:
        type: number
        required: true
      firstName:
        type: string
      lastName:
        type: string
      sex:
        type: string
        required: false
      age?:
        type: number
      department:
        type: string
        required: true