#%RAML 1.0 Library

types:
  coursesRequest:
    properties:
      courseId:
        type: number
      courseName:
        type: string
      code:
        type: any
      creditHours:
        type: number