#%RAML 1.0 Library

types:
  registerCourseRequest:
    properties:
      courseId:
        type: number
        required: true
      courseName:
        type: string
      code:
        type: any
        required: false
      creditHours:
        type: number
        required: true